CREATE TABLE IF NOT EXISTS weather (
    "time" TIMESTAMPTZ,
    "weather_code" INTEGER,
    "temperature_2m_max" FLOAT,
    "temperature_2m_min" FLOAT,
    "temperature_2m_mean" FLOAT,
    "apparent_temperature_max" FLOAT,
    "apparent_temperature_min" FLOAT,
    "apparent_temperature_mean" FLOAT,
    "sunrise" TIMESTAMPTZ,
    "sunset" TIMESTAMPTZ,
    "daylight_duration" FLOAT,
    "sunshine_duration" FLOAT,
    "precipitation_sum" FLOAT,
    "rain_sum" FLOAT,
    "snowfall_sum" FLOAT,
    "precipitation_hours" FLOAT,
    "wind_speed_10m_max" FLOAT,
    "wind_gusts_10m_max" FLOAT,
    "wind_direction_10m_dominant" INTEGER,
    "shortwave_radiation_sum" FLOAT,
    "et0_fao_evapotranspiration" FLOAT,
    "location_id" INTEGER,
    "record_id" SERIAL,
    PRIMARY KEY("record_id"),
    FOREIGN KEY("location_id") REFERENCES geo_location("id")
);